### ISSUE TITLE
Line buffering issue with stdout

### ISSUE THREAD

**Issue by MarkMcCaskey** [CraneStation/wasi-libc#102]
Hello!

I have some C code that I'm compiling with clang 8.0 and a sysroot compiled from master.

```C
int print_random_number_of_length(int size)
{
        //setbuf(stdout, NULL);
        char* before = "before";
        host_print(before, strlen(before));

        puts("ABC\n ");
        printf("FOUND SIZE %d\n", size);
        printf("FOUND SIZE %d\n", size);
        printf("defg\n");
        while (size > 0) {
                int digit = random() % 10;
                putchar(digit + '0');
                --size;
        }

        printf("\n");
        //fflush(stdout);
        char* after = "after";
        host_print(after, strlen(after));
        return 0;
}
```

And here's a trace:

```
PRINTING FROM THE HOST: "before"
PRINTING FROM THE HOST: "after"
<call to wasi::fd_write: fd=1>
ABC
 
FOUND SIZE 2
FOUND SIZE 2
defg
75
```

There are a number of things going on here:

- The host call, `host_print` prints the string using printf with a terminating new line.
- clang changes calls to `printf` with a static string into calls to `puts`
- wasi::fd_write is only called once; this is not a buffering issue in the runtime
- writes to stdout are buffered despite new lines: notice that the host calls come before the other prints.  Additionally, I've verified that it hasn't reordered the print statements in the generated Wasm.
- stdout seems to be correctly set to be line buffered: https://github.com/CraneStation/wasi-libc/blob/master/libc-top-half/musl/src/stdio/stdout.c#L11

The following things make it work correctly:

- uncommenting the `fflush(stdout)`
- uncommenting `setbuf(stdout, NULL);`
- passing in an argument large enough that about 1000 bytes are written

I spent some time looking into this, but ran into some issues and didn't want to spend too much time on this before asking for help.

I'm happy to fix this and submit a patch, but I got a bit lost in the code and print statements weren't working in all the places I'd like them to to quickly debug the issue.  I'd really appreciate any pointers in the right direction you all can give!

edit:

I'm using `clang source.c -Os -o wasi_example.wasm --target=wasm32-wasi -Wl,--allow-undefined -Wl,--export-all` to compile in case that helps.

**Comment by michaelvoronov** [comment]
I am just guessing, but as far as I know, in musl line-buffered (lbf = '\n') or non-buffered mode (lbf = -1) is completely depends on the type of device. So, for terminals it is enabled by default, but for other it is implementation specific and musl mainteiners recommend to explicitly set it. Then it seems that in WASI it is determined by `__isatty` function ([here](https://github.com/CraneStation/wasi-libc/blob/9bb4cc5c411af8453cbef69c137a4c2337714d89/libc-top-half/musl/src/stdio/__fdopen.c#L67) and [here](https://github.com/CraneStation/wasi-libc/blob/24792713d7e31cf593d7e19b943ef0c3aa26ef63/libc-top-half/musl/src/stdio/__stdout_write.c#L17)).

In its turn, `__isatty` uses `__wasi_fd_fdstat_get ` to [check](https://github.com/CraneStation/wasi-libc/blob/320054e84f8f2440def3b1c8700cedb8fd697bf8/libc-bottom-half/sources/isatty.c#L14) that file has `__WASI_FILETYPE_CHARACTER_DEVICE` type. But wasmer doesn't return this type of [device](https://github.com/wasmerio/wasmer/blob/38078173d3aac0950fcec28708058fb50c6c0cad/lib/wasi/src/state/mod.rs#L741). So probably the issue could be in this fact. But it is just my guessing and it is difficult to answer without full source code.

**Comment by MarkMcCaskey** [comment]
@michaelvoronov Thank you!  That's extremely helpful!  It looks like this probably isn't a bug in wasi-libc then, sorry about the noise!
