### ISSUE TITLE
Duplicate symbol when using no arguments version of main with lto

### ISSUE THREAD

**Issue by caspervonb** [CraneStation/wasi-libc#137]
The linker is fussing about duplicate symbol __original_main when trying to use main with the signature `int main(void)`

Related https://github.com/CraneStation/wasi-libc/pull/112

**Comment by sunfishcode** [comment]
Thanks for the report! I'm unfortunately not able to reproduce this. Would you mind posting more information, such as your full test case, the platform you're on, and the command-line arguments you're compiling and linking with?

**Comment by caspervonb** [comment]
The test program was just a bare-bones main.

```
int main(void) {
  return 0;
}
```

But it seems that link time optimisations is the culprit, the following fails

```
/opt/wasi-sdk-8.0/bin/clang --target=wasm32-wasi --sysroot=/opt/wasi-sdk-8.0/share/wasi-sysroot -flto  -o obj/main.o -c src/main.c

/opt/wasi-sdk-8.0/bin/clang --target=wasm32-wasi --sysroot=/opt/wasi-sdk-8.0/share/wasi-sysroot -flto  -o main.wasm obj/main.o
wasm-ld: error: duplicate symbol: __original_main
```

But if i remove -flto it works fine.

```
/opt/wasi-sdk-8.0/bin/clang --target=wasm32-wasi --sysroot=/opt/wasi-sdk-8.0/share/wasi-sysroot -o obj/main.o -c src/main.c
/opt/wasi-sdk-8.0/bin/clang --target=wasm32-wasi --sysroot=/opt/wasi-sdk-8.0/share/wasi-sysroot -o main.wasm obj/main.o
```

**Comment by sunfishcode** [comment]
Thanks! I've now submitted #138 with a fix.
