### ISSUE TITLE
64bit woes in Chromium

### ISSUE THREAD

**Issue by caspervonb** [CraneStation/wasi-libc#158]
Chromium is complains about `clock_t` being a `long long` of 64bits when targeting `wasm32-wasi`.

```
TypeError: wasm function signature contains illegal type
    at clock (wasm-function[20]:0x24c5)
    at __original_main (wasm-function[11]:0x29d)
    at _start (wasm-function[10]:0x241)
    at test.html:66
```

Same would apply to anything that relies on other `long long` typedefs like
  - __wasi_device_t
  - __wasi_dircookie_t
  - __wasi_filesize_t
  - __wasi_inode_t
  - __wasi_rights_t
  - __wasi_timestamp_t
  - __wasi_userdata_t

Upstream llvm issue? As in should the wasm32-* targets be spitting out i64 for these?

**Comment by sbc100** [comment]
This is not a chromium issue but more a general issue with embedding wasm in JS today.   See https://github.com/WebAssembly/WASI/issues/54 for more background here.

In the long run BigInt support in the JS engines will be widely the available this issue should go away.

In the near term, if you want to run WASI programs on the web (or in node) you will need to either enable the experimental BigInt support in the engines, or run some kind of post-processing tool on the wasm binary to remove all 64 bit integers from the API.   binaryen has passes that can do this for example which is how emscripten handles this problem.

**Comment by caspervonb** [comment]
> This is not a chromium issue but more a general issue with embedding wasm in JS today. See WebAssembly/WASI#54 for more background here.
> In the long run BigInt support in the JS engines will be widely the available this issue should go away.
> In the near term, if you want to run WASI programs on the web (or in node) you will need to either enable the experimental BigInt support in the engines, or run some kind of post-processing tool on the wasm binary to remove all 64 bit integers from the API. binaryen has passes that can do this for example which is how emscripten handles this problem.

Yeah I was a bit puzzled as to why a 32bit target would be using explicit 64bit integers that the MVP doesn't support.

Appreciate the tip as I did not know that wasm-opt had this pass! Exactly what I wanted.

**Comment by sbc100** [comment]
The WebAssembly MVP supports 64-bit integers just fine.  It is JS that doesn't (didn't) support them, and WASI is not primarily targeting JS.
