### ISSUE TITLE
is WASI capable of doing networking?

### ISSUE THREAD

**Issue by andrewrk** [CraneStation/wasi-libc#71]
I don't see how these functions would work:
 * socket
 * accept
 * bind
 * listen

**Comment by sunfishcode** [comment]
Right, those functions are not currently defined.in WASI libc.

It is possible they could be added in the future, by making sockets something that get passed into a program, or possibly by providing a capability to create/bind/accept/listen to certain addresses/ports/etc. to a program.

**Comment by Qix-** [comment]
Libc doesn't include networking functionality, those are instead provided by the system for which you are developing. I don't think wasi-libc should even include those, but instead focus on being a complete and stable WASM libc IMO.

**Comment by sunfishcode** [comment]
The place to add networking support is [WASI itself](https://github.com/WebAssembly/WASI/), which I assume will happen at some point. Once that's done, we can discuss how to add `bind`, `accept`, `socket`, and `listen` in WASI libc on top of that.
