### ISSUE TITLE
`__wasilibc_init_preopen` not getting called at startup

### ISSUE THREAD

**Issue by OhadRau** [CraneStation/wasi-libc#73]
Was encountering an assertion failure in `fopen()` and managed to trace it down to `get_shared_map()` where `assert(global_map)` would always fail. It seems like `__wasilibc_init_preopen` never initializes the `global_map` here causing `get_shared_map` (and by extension `fopen`) to always fail. As a quick fix, simply calling the init procedure when the `global_map` is `NULL` will work.

**Comment by sbc100** [comment]
`__wasilibc_init_preopen` is called unconditionally during `_start` which is defined in `libc-bottom-half/crt/crt1.c`.

Are you somehow not using or not calling the normal crt1.c start function?

**Comment by OhadRau** [comment]
Interesting, looks like _start was indeed not being called based on how I linked the file unless I explicitly added `--entry=main` to the `wasm-ld` flags. Thanks!
