### ISSUE TITLE
FE_DOWNWARD, FE_UPWARD and FE_TOWARDZERO are not defined

### ISSUE THREAD

**Issue by saghul** [CraneStation/wasi-libc#85]
Hey there! I'm having quite some fun with WASI, kudos for the nice work!

Today while porting a library (QuickJS specifically) I ran into this. As the title says, those are not defined in `wasi-sdk/share/sysroot/include/bits/fenv.h`. I manually defined them and compilation continued though :-)

**Comment by sunfishcode** [comment]
Thanks! WebAssembly itself only supports round-to-nearest. It doesn't support any other rounding modes. To reflect this, WASI only defines `FE_TONEAREST`, and not `FE_DOWNWARD`, `FE_UPWARD` and `FE_TOWARDZERO`.

You're welcome to manually define them, although note that this won't enable the platform to respect these rounding modes, so you may see floating-point results with incorrect rounding.

**Comment by saghul** [comment]
Ah, this is good to know! Do you see the other modes ever making it to the spec?

**Comment by sunfishcode** [comment]
It's possible. There are some ideas about how this might work sketched out [here](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#full-ieee-754-2008-conformance), though at this time there isn't yet an active proposal for them, so it's difficult to say when this might advance.

**Comment by saghul** [comment]
Thanks for the insight! Feel free to close this if appropriate. Cheers!
