### ISSUE TITLE
sub-optimal math functions

### ISSUE THREAD

**Issue by sbc100** [CraneStation/wasi-libc#92]
Currently we are including the C implementations of several math function:

- rint
- rintf
- copysignf
- floor
- ceil
- trunc
- fabs
- copysign
- sqrt

This means that any code compiled with `-fno-builtin` will end up with sub-optimal implementations and because wasi-libc itself is compiled with `-fno-builtin` any internal references to these functions will be sub-optimal.

This was recently fixed in emscripten via: https://github.com/emscripten-core/emscripten/pull/9239 https://github.com/emscripten-core/emscripten/pull/9250

However, a cleaner fix might be to use arch-specific implementations like, for example:
`./libc-top-half/musl/src/math/i386/rintf.s`

**Comment by sunfishcode** [comment]
This was fixed in https://github.com/CraneStation/wasi-libc/commit/16450763ebbc5b5c582d3c5bfefc1c377e2fb3ce.

**Comment by sbc100** [comment]
Ah thanks, sorry couldn't find the fix
